/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mazdausa.mmg.constants;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

/**
 * This Class will contain all the application specific constants.
 * @author Pankaj Bhatt
 * @version 1.0
 *
 */
@Component
@Scope(value="singleton")
public class ApplicationConstants {

      
    public final String STATUS_SUCCESS="success";
    public final String STATUS_FAILURE="failure";
    
    public static final String DOC_TYPE_PDF="PDF";
    public static final String DOC_TYPE_VIDEO="VIDEO";
    public static final String DOC_TYPE_TEXT="TEXT";

    public static final String RESULT="result";
    public static final String DEFAULT_VALUE="-1";
    public static final String RESULT_STATUS_OK_TEXT="status=\"ok\"";
    public static final String RESULT_STATUS="status";
    public static final String RESULT_STATUS_OK="OK";
    public static final String PASSWORD_CHANGE_OK_TEXT="\"result\":\"ok\"";
    public static final String PASSWORD_CHANGE_FAIL_TEXT="\"result\":\"fail\"";
    public static final String RESULT_STATUS_VALIDATIONERROR="validation_error";
    public static final String RESULT_STATUS_SYSTEMERROR="system_error";
    public static final String RESULT_STATUS_EMAILNOTFOUND  ="email_not_found";
    public static final String RESULT_STATUS_EMAILEXISTS  ="email_exists";
    public static final String RESULT_STATUS_LOGINFAILED  ="login_failed";
    public static final String RESULT_DATA="data";
    public static final String USER_ADMIN="Admin";
    public static final String USER_APPLICATION="App";
    public static final String CONSTANT_OWNER_YES="Y";
    public static final String DOLLAR="$";
    public static final String PERCENTAGE="%";
    public static final String COUPON_PRICE_FREE="FREE";
    public static final String COUPON_PRICE_OFF="OFF";

    public static final String DATE_FORMAT_MMDDYYYY="MM/dd/yyyy";

    /**
     * IPHONE PUSH SPECIFIC PARAMETERS.
     */
    @Value("${IPHONE_PUSH_MAX_LIMIT}")
    public int IPHONE_PUSH_MAX_LIMIT;
    @Value("${IPHONE_PUSH_NOTIFICATION_ON}")
    public boolean IPHONE_PUSH_NOTIFICATION_ACTIVE;
    @Value("${IPHONE_PUSH_APNS_CERTIFICATE_LOCATION}")
    public String IPHONE_PUSH_CERTIFICATE_LOCATION;
    @Value("${IPHONE_PUSH_APNS_CERTIFICATE_PASSWORD}")
    public String IPHONE_PUSH_CERTIFICATE_PASSWORD;

	@Value("${MMG.RECALL.PUSHNOTIFICATION.ENABLED}")
    public boolean MMG_RECALL_PUSHNOTIFICATION_ENABLED;


    // List of Constants that belongs to Dealer.

    // All the Dealer Related Constants that are present int he DEALER Search are being defined Here.
    public static final String XML_DEALERS="dealers";
    public static final String XML_DEALER="dealer";
    public static final String XML_DEALERCOUNT="dealerCount";
    public static final String XML_DEALER_ATTRIBUTE_ID="id";
    public static final String XML_DEALER_ATTRIBUTE_NAME="name";
    public static final String XML_DEALER_ATTRIBUTE_URL="url";
    public static final String XML_DEALER_ADDRESS="address";
    public static final String XML_DEALER_ADDRESS_STREET="street";
    public static final String XML_DEALER_ADDRESS_CITY="city";
    public static final String XML_DEALER_ADDRESS_STATE="state";
    public static final String XML_DEALER_ADDRESS_ZIP="zip";
    public static final String XML_DEALER_ADDRESS_PHONE="phone";
    public static final String XML_DEALER_DISTANCE="distance";
    public static final String XML_DEALER_LOCATION="location";
    public static final String XML_DEALER_SMS="sms";
    public static final String XML_DEALER_SERVICE_APPOINTMENT_URL="serviceUrl";
    public static final String XML_DEALER_MDOL="mdol";
    public static final String XML_DEALER_ACCOLADES="accolades";
    public static final String XML_DEALER_ACCOLADE="accolade";
    public static final String XML_DEALER_ACCOLADE_ID="id";
    public static final String XML_DEALER_ACCOLADE_NAME="name";
    public static final String XML_DEALER_ACCOLADE_DESCRIPTION="description";

    public static final String XML_VEHICLE_MAINTENANCE="maintenance";
    public static final String XML_VEHICLE_MAINTENANCE_ATTRIBUTE_STATUS="status";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_DRIVINGHABIT="drivingHabit";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE="maintenanceSchedule";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS="intervalItemLists";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST="intervalItemList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL="interval";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_CLEANLISTS="cleanList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_CLEANLISTS_CLEANELEMENT="cleanElement";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_CLEANLISTS_CLEANELEMENT_ITEMANE="itemName";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_LUBRICATELISTS="lubricateList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_LUBRICATELISTS_LUBRICATEELEMENT="lubricateElement";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_LUBRICATELISTS_LUBRICATEELEMENT_ITEMNAME="itemName";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_REPLACELIST="replaceList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_REPLACELIST_REPLACELEMENT="replaceElement";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_REPLACELIST_REPLACELEMENT_ITEMNAME="itemName";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_INSPECTLIST="inspectList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_INSPECTLIST_INSPECTELEMENT="inspectElement";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_INSPECTLIST_INSPECTELEMENT_ITEMNAME="itemName";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_INSPECTLIST_INSPECTELEMENT_ITEMFOOTNAME="itemFootnote";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_TIGHTENLIST="tightenList";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_TIGHTENLIST_TIGHTENELEMENT="tightenElement";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_IILISTS_ITLIST_INTERVAL_TIGHTENLIST_TIGHTENELEMENT_ITEMNAME="itemName";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_MAINTENANCENOTES="maintenanceNotes";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCESCHEDULE_MAINTENANCENOTES_MAINTENANCENOTE="maintenanceNote";
    
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCENONINTERVAL="maintenanceNonInterval";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCENONINTERVAL_ELEMENT_NONINTERVALITEM="nonIntervalItem";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCENONINTERVAL_ELEMENT_NONINTERVALITEM_ITEMDESCRIPTION="itemDescription";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCENONINTERVAL_ELEMENT_NONINTERVALITEM_NONINTERVALDESCRIPTION="nonIntervalDesc";
    public static final String XML_VEHICLE_MAINTENANCE_ELEMENT_MAINTENANCENONINTERVAL_ELEMENT_NONINTERVALITEM_ITEMFOOTNOTE="itemFootnote";

    public static final String XML_VEHICLE_MAINTENANCE_ERROR="error";
    public static final String XML_VEHICLE_MAINTENANCE_ERROR_MESSAGE="message";
    public static final String XML_VEHICLE_MAINTENANCE_ERROR_CODE="code";

    // Vehicle Details XML Elements.
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY="vinInquiry";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE="vehicle";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_VIN="vin";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_MODELYEAR="modelYear";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_CARLINE="carline";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_TRIM="trim";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_ENGINE="engine";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_TRANSMISSION="transmission";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_EXTCOLOR="extColor";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_INTCOLOR="intColor";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_VEHICLE_ATTRIBUTE_DESCRIPTION="description";
    public static final String XML_VEHICLE_INFORMATION_VININQUIRY_ELEMENT_ERROR="error";

    // Vehicle Details information XML Elements.
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET="vehicleresultset";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE="vehicle";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_VIN="vin";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_CARLINE="carline";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_CARLINE_CARLINECODE="carlinecode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_CARLINE_CARLINEDESC="carlinedesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL="model";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_MODELYEAR="mdlyear";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_MODELCODE="mdlcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_TRIM="trim";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_ENGINE="engine";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_ENGINE_ENGINEDESC="engdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_TRANSMISSION="transmission";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_TRANSMISSION_TRANSMISSIONDESC="transdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_DRIVECODE="drivecode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_SEATING="seating";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_SEATING_ROWS="rows";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_MODEL_SEATING_PASSENGERS="passengers";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP="optiongroup";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_MSC="MSC";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE="package";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE_PACKAGECODE="pkgcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE_PACKAGEDESC="pkgdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE_PACKAGEOPT="pkgopt";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE_PACKAGEOPT_PKGOPTCODE="pkgoptcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_PACKAGE_PACKAGEOPT_PKGOPTDESC="pkgoptdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_OPTION="option";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_OPTION_OPTCODE="optcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_OPTIONGROUP_OPTION_OPTDESC="optdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_EXTCOLOR="extcolor";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_EXTCOLOR_EXTCODE="extcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_EXTCOLOR_EXTDESC="extdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_INTCOLOR="intcolor";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_INTCOLOR_INTCODE="intcode";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_INTCOLOR_INTDESC="intdesc";
    public static final String XML_VEHICLE_DETAIL_INFORMATION_VEHICLERESULTSET_VEHICLE_ERROR="error";


    // All Vehicle Recall Alert Related Specific parameters.
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT="recallInquiryResult";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_ERROR="error";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_ATTRIBUTE_VIN="VIN";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_RECALLORSSP="recallOrSSP";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_RECALLORSSP_RECALLSSPNO="recallSSPNo";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_RECALLORSSP_RECALLSSPDESC="recallSSPDesc";
    public static final String XML_VEHICLE_RECALLALERT_RECALLINQUIRYRESULT_RECALLORSSP_STARTDATE="startDate";


    // All the XML Elements corressponding to get COUOPONS by DEALER ID
    public static final String XML_DEALER_COUPONS_RESULT="result";
    public static final String XML_DEALER_COUPONS_RESULT_ATTRIBUTE_STATUS="status";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS="coupons";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON="coupon";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_ATTRIBUTE_ID="id";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_TITLE="title";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_DEAL="deal";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_DESCRIPTIONS="descriptions";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_DESCRIPTIONS_DESCRIPTION="description";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_SERVICES="services";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_SERVICES_SERVICE="service";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_DISCLAIMER="disclaimer";
    public static final String XML_DEALER_COUPONS_RESULT_COUPONS_COUPON_EXCEPTION="exception";
    public static final String XML_DEALER_COUPONS_RESULT_ERRORS="errors";
    public static final String XML_DEALER_COUPONS_RESULT_ERRORS_ERROR="error";
    public static final String XML_DEALER_COUPONS_RESULT_ERRORS_ERROR_ERRORS="errors";
    public static final String XML_DEALER_COUPONS_RESULT_ERRORS_ERROR_ERRORS_ATTRIBUTE_CODE="code";


    public static final String XML_ERROR="error";
    public static final String XML_ERROR_CODE="code";
    public static final String XML_SUCCESS_CUSTOMERID="customerId";





    // The Below constants contains a list of WEB/REST SERVICES.

    @Value("${MMG.SERVICE.REST.SECURITY.PARAMETER.NAME}")
    public String SERVICE_REST_SECURITY_PARAMETER_NAME;

    @Value("${MMG.SERVICE.REST.SECURITY.PARAMETER.VALUE}")
    public String SERVICE_REST_SECURITY_PARAMETER_VALUE;
    
    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.ZIPCODE.LIMITED}")
    public String SERVICE_REST_DEALERLOCATOR_ZIPCODE_SEARCH_LIMITED;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.ZIPCODE}")
    public String SERVICE_REST_DEALERLOCATOR_SEARCH_ZIPCODE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.ZIPCODE_DISTANCE}")
    public String SERVICE_REST_DEALERLOCATOR_SEARCH_ZIPCODE_DISTANCE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.ZIPCODE.DISTANCE.MAZDASPEEDONLY}")
    public String SERVICE_REST_DEALERLOCATOR_SEARCH_ZIPCODE_DISTANCE_MAZDASPEEDONLY;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.STATE_CITY}")
    public  String SERVICE_REST_DEALERLOCATOR_SEARCH_STATE_CITY;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.STATE_CITY_DISTANCE}")
    public  String SERVICE_REST_DEALERLOCATOR_SEARCH_STATE_CITY_DISTANCE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.STATE_CITY_DISTANCE_SPEEDONLY}")
    public  String SERVICE_REST_DEALERLOCATOR_SEARCH_STATE_CITY_DISTANCE_SPEEDONLY;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.NAME}")
    public String SERVICE_REST_DEALERLOCATOR_SEARCH_NAME;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.LONGLAT}")
    public String SERVICE_REST_DEALERLOCATOR_SEARCH_LONGLAT;

    @Value("${MMG.SERVICE.REST.USER.REGISTRATION}")
    public  String SERVICE_REST_USER_REGISTRATION;

    @Value("${MMG.SERVICE.REST.USER.LOGIN}")
    public  String SERVICE_REST_USER_LOGIN;

    @Value("${MMG.SERVICE.REST.USER.FORGOTPASSWORD}")
    public  String SERVICE_REST_USER_FORGOTPASSWORD;

    @Value("${MMG.SERVICE.REST.USER.CHANGEPASSWORD}")
    public  String SERVICE_REST_USER_CHANGEPASSWORD;
    
    @Value("${MMG.SERVICE.REST.USER.RESETPASSWORDLINK}")
    public  String SERVICE_REST_USER_RESETPASSWORDLINK;
    
    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.VIN_AND_DRIVINGHABIT}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_VIN_DRIVINGHABIT;

    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.MODEL_YEAR_DRIVINGHABIT}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_MODEL_YEAR_DRIVINGHABIT;

    @Value("${MMG.SERVICE.REST.VEHICLE.RECALLALERT}")
    public String SERVICE_REST_VEHCILE_RECALLALERT;

    @Value("${MMG.SERVICE.FUSION.AUTHORIZATION.KEY}")
    public String SERVICE_FUSION_AUTHORIZATION_KEY;
    
    @Value("${MMG.SERVICE.FUSION.AUTHORIZATION.USER}")
    public String SERVICE_FUSION_AUTHORIZATION_USER;
    
    @Value("${MMG.SERVICE.FUSION.AUTHORIZATION.PASSWORD}")
    public String SERVICE_FUSION_AUTHORIZATION_PASSWORD;
    
    @Value("${MMG.SERVICE.REST.SERVICE.HISTORY.INFO}")
    public String SERVICE_REST_SERVICE_HISTORY_INFO;
    
    @Value("${MMG.SERVICE.REST.GET.USER.VEHICLES}")
    public String SERVICE_REST_GET_USER_VEHICLES;
    
    @Value("${MMG.SERVICE.REST.SET.SERVICING.DEALER}")
    public String SERVICE_REST_SET_SERVICING_DEALER;
    
    @Value("${MMG.SERVICE.REST.UPDATE.OWNERSHIP}")
    public String SERVICE_REST_UPDATE_OWNERSHIP;
    
    @Value("${MMG.SERVICE.REST.GET.USER.DETAILS}")
    public String SERVICE_REST_GET_USER_DETAILS;
    
    @Value("${MMG.SERVICE.REST.UPDATE.CUSTOMER.DETAILS}")
    public String SERVICE_REST_UPDATE_CUSTOMER_DETAILS;
    
    @Value("${MMG.SERVICE.REST.SERVICE.RECORD.INFO}")
    public String SERVICE_REST_SERVICE_RECORD_INFO;

    @Value("${MMG.SERVICE.REST.SERVICE.RECORD.INFO.ADD}")
    public String SERVICE_REST_SERVICE_RECORD_INFO_ADD;
    
    @Value("${MMG.SERVICE.REST.SERVICE.RECORD.INFO.DELETE}")
    public String SERVICE_REST_SERVICE_RECORD_INFO_DELETE;
    
    @Value("${MMG.SERVICE.REST.SERVICE.RECORD.INFO.UPDATE}")
    public String SERVICE_REST_SERVICE_RECORD_INFO_UPDATE;
    
    @Value("${MMG.SERVICE.REST.USER.WINDOWSTICKER}")
    public String SERVICE_REST_USER_WINDOWSTICKER;

    @Value("${MMG.SERVICE.REST.USER.AGERORSAAPI}")
    public String SERVICE_REST_USER_AGERORSAAPI;
    
    @Value("${MMG.SERVICE.REST.USER.AGERORSAAPI.KEY}")
    public String SERVICE_REST_USER_AGERORSAAPI_KEY;
    
    /**
    * List of Parameter constants to be passed in above URL's.
    */
    
    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.ZIPCODE}")
    public String DEALER_SEARCH_URL_PARAMETER_ZIPCODE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.DISTANCE}")
    public String DEALER_SEARCH_URL_PARAMETER_DISTANCE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.MAZDASPEEDONLY}")
    public String DEALER_SEARCH_URL_PARAMETER_SPEEDONLY;
    
    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.STATE}")
    public String DEALER_SEARCH_URL_PARAMETER_STATE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.CITY}") 
    public String DEALER_SEARCH_URL_PARAMETER_CITY;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.LONGITUDE}")
    public String DEALER_SEARCH_URL_PARAMETER_LONGITUDE;

    @Value("${MMG.SERVICE.REST.DEALERLOCATOR.SEARCH.PARAMETR.LATITUDE}") 
    public String DEALER_SEARCH_URL_PARAMETER_LATITUDE;


    @Value("${MMG.SERVICE.REST.USER.PARAMETER.FIRSTNAME}")
    public  String SERVICE_REST_USER_PARAMETER_FIRSTNAME;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.LASTNAME}")
    public  String SERVICE_REST_USER_PARAMETER_LASTNAME;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.EMAIL}")
    public  String SERVICE_REST_USER_PARAMETER_EMAIL;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.EMAILCONFIRM}")
    public  String SERVICE_REST_USER_PARAMETER_EMAILCONFIRM;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.PASSWORD}")
    public  String SERVICE_REST_USER_PARAMETER_PASSWORD;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.PASSWORDCONFIRM}")
    public  String SERVICE_REST_USER_PARAMETER_PASSWORDCONFIRM;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.STREETADDRESS}")
    public  String SERVICE_REST_USER_PARAMETER_STREETADDRESS;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.CITY}")
    public  String SERVICE_REST_USER_PARAMETER_CITY;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.STATE}")
    public  String SERVICE_REST_USER_PARAMETER_STATE;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.ZIP}")
    public  String SERVICE_REST_USER_PARAMETER_ZIP;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.CELLNUMBER}")
    public  String SERVICE_REST_USER_PARAMETER_CELLNUMBER;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.VIN}")
    public  String SERVICE_REST_USER_PARAMETER_VIN;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.MILEAGE}")
    public  String SERVICE_REST_USER_PARAMETER_MILEAGE;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.USERNAME}")
    public  String SERVICE_REST_USER_PARAMETER_USERNAME;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.CURRENTPASSWORD}")
    public  String SERVICE_REST_USER_PARAMETER_CURRENTPASSWORD;
    
    @Value("${MMG.SERVICE.REST.USER.PARAMETER.NEWPASSWORD}")
    public  String SERVICE_REST_USER_PARAMETER_NEWPASSWORD;
    
    @Value("${MMG.SERVICE.REST.USER.PARAMETER.DEALERID}")
    public  String SERVICE_REST_USER_PARAMETER_DEALERID;
    
    @Value("${MMG.SERVICE.REST.USER.PARAMETER.MODELCODE}")
    public  String SERVICE_REST_USER_PARAMETER_MODELCODE;

    @Value("${MMG.SERVICE.REST.USER.PARAMETER.MODELYEAR}")
    public  String SERVICE_REST_USER_PARAMETER_MODELYEAR;

    @Value("${MMG.SERVICE.REST.VEHICLE.RECALLALERT.PARAMETER.VIN}")
    public  String SERVICE_REST_VEHICLE_RECALLALERT_PARAMETER_VIN;

    // Parameter related to Vehicle Maintenance Schedule.
    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.PARAMETER.VIN}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_PARAMETER_VIN;

    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.PARAMETER.DRIVINGHABIT}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_PARAMETER_DRIVINGHABIT;

    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.PARAMETER.MODEL}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_PARAMETER_MODEL;

    @Value("${MMG.SERVICE.REST.USER.VIN.MAINTENANCE_SCHEDULE.PARAMETER.YEAR}")
    public String SERVICE_REST_USER_VECHILE_MAINTENANCE_SCHEDULE_PARAMETER_YEAR;

    //******** VEHICLE RELATED SEARVICES. ************************

    @Value("${MMG.SERVICE.REST.VEHICLE.INFORMATION}")
    public String SERVICE_REST_VEHICLE_INFORMATION;

    @Value("${MMG.SERVICE.REST.VEHICLE.DETAIL.INFORMATION}")
    public String SERVICE_REST_VEHICLE_DETAIL_INFORMATION;

    // Parameter related to Vehicle Detail services.
    @Value("${MMG.SERVICE.REST.VEHICLE.INFORMATION.PARAMETER.ID}")
    public String SERVICE_REST_VEHICLE_INFORMATION_PARAMETER_ID;

    @Value("${MMG.SERVICE.REST.VEHICLE.INFORMATION.PARAMETER.VIN}")
    public String SERVICE_REST_VEHICLE_INFORMATION_PARAMETER_VIN;

    @Value("${MMG.SERVICE.REST.VEHICLE.INFORMATION.PARAMETER.TYPE}")
    public String SERVICE_REST_VEHICLE_INFORMATION_PARAMETER_TYPE;

    public static final String XML_VEHICLE_INFORMATION_PARAMETER_ID_DEFAULT_VALUE="INQUIRE";
    public static final String XML_VEHICLE_INFORMATION_PARAMETER_TYPE_DEFAULT_VALUE="B2B";

    // All the Services REST related to Dealer COUPONS.
    @Value("${MMG.SERVICE.REST.DEALER.GETCOUPONS.DEALERID}")
    public String SERVICE_REST_DEALER_GETCOUPONS_DEALERID;

    @Value("${MMG.SERVICE.REST.DEALER.GETCOUPONS.DEALERID.COUPONID}")
    public String SERVICE_REST_DEALER_GETCOUPONS_DEALERID_COUPONID;

    @Value("${MMG.SERVICE.REST.DEALER.GETCOUPONS.PARAMETER.DEALERID}")
    public String SERVICE_REST_DEALER_GETCOUPONS_PARAMETER_DEALERID;

    @Value("${MMG.SERVICE.REST.DEALER.GETCOUPONS.PARAMETER.COUPONID}")
    public String SERVICE_REST_DEALER_GETCOUPONS_PARAMETER_COUPONID;

    // General Constants.
    public static final String OAUTH_TOKEN_HEADER="OAUTH_TOKEN";
    public static final String JSESSION_HEADER="jsessionid";
    public static final String GUID_HEADER="guid";
    public static final String USER_AGENT="user-agent";
    


   public static final String MAZDA_SERVICE_RESPONSE_OK="ok";
   public static final String MAZDA_SERVICE_RESPONSE_FAIL="fail";


   public static final String PARAMETER_DEFAULT_VALUE="-1";
   public static final String YES="yes";
   public static final String NO="no";



   /**
    * ALL the SOAP Web Services and their request, response name description.
    */
   // Header Description.
   @Value("${MMG.SERVICE.SOAP.HEADER.SECURITYTOKEN.NAME}")
   public String SERVICE_SOAP_HEADER_SECURITYTOKEN_NAME;

   @Value("${MMG.SERVICE.SOAP.HEADER.SECURITYTOKEN.VALUE}")
   public String SERVICE_SOAP_HEADER_SECURITYTOKEN_VALUE;

   @Value("${MMG.SERVICE.SOAP.HEADER.GENERATOR.NAME}")
   public String SERVICE_SOAP_HEADER_GENERATOR_NAME;

   @Value("${MMG.SERVICE.SOAP.HEADER.GENERATOR.VALUE}")
   public String SERVICE_SOAP_HEADER_GENERATOR_VALUE;

   @Value("${MMG.SERVICE.SOAP.HEADER.ACTOR.NAMESPACE}")
   public String SERVICE_SOAP_HEADER_ACTOR_NAMESPACE;

   @Value("${MMG.SERVICE.SOAP.HEADER.NAMESPACE}")
   public String SERVICE_SOAP_HEADER_NAMESPACE;

   @Value("${MMG.SERVICE.SOAP.REQUEST.NAMESPACE}")
   public String SERVICE_SOAP_REQUEST_NAMESPACE;

   @Value("${MMG.SERVICE.SOAP.REQUEST.NAMESPACE.ID}")
   public String SERVICE_SOAP_REQUEST_NAMESPACE_ID;


   // Get Vehicles Web Service
   // 1.
   @Value("${MMG.SERVICE.REST.GETVEHICLES}")
   public String SERVICE_REST_GETVEHICLES;

   @Value("${MMG.SERVICE.REST.GETVEHICLES.ACTION}")
   public String SERVICE_REST_GETVEHICLES_ACTION;

   public static final String SERVICE_REST_GETVEHICLES_REQUESTELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";
   public static final String SERVICE_REST_GETVEHICLES_RESPONSEELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";

   // Request Parameter for GET VEHICLES
   public static final String XML_REST_GETVEHICLES_REQUEST_PARAMETER_GETVEHICLES="getVehicles";
   public static final String XML_REST_GETVEHICLES_REQUEST_PARAMETER_GETVEHICLES_CUSTOMERID="custId";

   // Response Parameter.
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES="getVehiclesResponse";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN="getVehiclesReturn";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_ERROR="error";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS="vehDetails";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_COUNT="count";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST="vehicleList";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE="Vehicle";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_CARLINECODE="carlineCode";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_CARLINEDESC="carlineDesc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_CURRENTOWNERFLAG="currentownerflag";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_DRIVECODE="driveCode";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE="engine";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_CAMSHAFT="camShaft";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_CYLROT="cylRot";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_ENGDESC="engDesc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_ENGTYPE="engType";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_CYLQTY="cylQty";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_DISPCC="dispcc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_HPQTY="hpQty";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_ENGINE_HPRPM="hprpm";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_EXTCOLORCODE="extColorCode";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_EXTCOLORDESC="extColorDesc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_INTCOLORCODE="intColorCode";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_INTCOLORDESC="intColorDesc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_LEASEMATURITYDATE="leaseMaturityDate";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_MDLCODE="mdlCode";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_MDLYEAR="mdlYear";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_PURCHASEDATE="purchaseDate";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_SEATINGPASSENGERS="seatingPassengers";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_SEATINGROWS="seatingRows";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_SERVICINGDEALERID="serviceDealerID";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_TRIM="trim";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_VIN="vin";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_TRANSMISSION="transmission";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_TRANSMISSION_SPEEDS="speeds";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_TRANSMISSION_TRANSDESC="transdesc";
   public static final String XML_REST_GETVEHICLES_RESPONSE_PARAMETER_GETVEHICLES_GETVEHICLESRETURN_VEHICLEDETAILS_VEHICLELIST_VEHICLE_TRANSMISSION_TRNTYPE="trntype";

   // 2. User Detail Request.

   @Value("${MMG.SERVICE.SOAP.GETUSERDETAIL}")
   public String SERVICE_SOAP_USERDETAILS;

   @Value("${MMG.SERVICE.SOAP.GETUSERDETAIL.ACTION}")
   public String SERVICE_SOAP_USERDETAILS_ACTION;

   public static final String SERVICE_REST_USERDETAILS_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_REST_USERDETAILS_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // Request Parameter for User Detail
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER="getOrInsertCustomer";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER="cust";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_VIN="vin";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_CUSTID="custID";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_EMAIL="email";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_FIRSTNAME="firstName";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_LASTNAME="lastName";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_SOURCE="source";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_STREET1ADDRESS="street1address";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_STREET2ADDRESS="street2address";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_ZIP="zip";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_CITY="city";
   public static final String XML_REST_USERDETAILS_REQUEST_PARAMETER_GETCUSTOMER_CUSTOMER_STATE="state";

   // Response Parameter for User Detail.
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE="getOrInsertCustomerResponse";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER="getOrInsertCustomerReturn";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_SALESDEALERID="salesDealerId";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_ERROR="error";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_CUSTID="custID";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DATAINSYNCHFLAG="dataInSynchFlag";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_EXISTINGCUSTOMERFLAG="existingCustFlag";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_ADDRESSTYPE="addressType";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_CITY="city";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_COUNTRY="country";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTCALL="doNotCall";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTCALLDATE="doNotCallDate";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTCONTACT="doNotContact";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTCONTACTDATE="doNotContactDate";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTEMAIL="doNotEmail";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_DONOTEMAILDATE="doNotEmailDate";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_EMAIL="email";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_EMAILTYPE="emailType";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_FIRSTNAME="firstName";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_HOMEPHONE="homePhone";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_INVALIDADDRESSFLAG="invalidAddressFlag";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_LASTNAME="lastName";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_MOBILEPHONE="mobilePhone";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_STATE="state";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_STREET1ADDRESS="street1address";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_STREET2ADDRESS="street2address";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_WORKPHONE="workPhone";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_WORKPHONEEXT="workPhoneExt";
   public static final String XML_REST_USERDETAILS_RESPONSE_PARAMETER_CUSTOMERRESPONSE_CUSTOMER_ZIP="zip";

   // 3 Vehicle Service Request.
   /*@Value("${MMG.SERVICE.SOAP.VEHICLE.SERVICEHISTORY}")
   public String SERVICE_SOAP_USER_VEHICLEHISTORY;

   @Value("${MMG.SERVICE.SOAP.VEHICLE.SERVICEHISTORY.ACTION}")
   public String SERVICE_SOAP_USER_VEHICLEHISTORY_ACTION;*/

   public static final String SERVICE_REST_USER_REQUEST_PARAMETER_REQUESTOR="requestor";
   public static final String SERVICE_REST_USER_REQUEST_PARAMETER_VERSION="version";
   public static final String SERVICE_REST_USER_REQUEST_PARAMETER_REQUESTID="requestId";
   
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_REQUESTELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSEELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";

   // List of Parameters for above.

   public static final String SERVICE_REST_USER_VEHICLEHISTORY_REQUEST_PARAMETER_SERVICEHISTORY="getServiceHistory";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_REQUEST_PARAMETER_SERVICEHISTORY_VIN="vin";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_REQUEST_PARAMETER_SERVICEHISTORY_CUSTID="custId";


   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE="getServiceHistoryResponse";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN="getServiceHistoryReturn";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS="vehServiceDetails";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_ERROR="error";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_COUNT="count";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST="serHistoryList";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE="Service";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_BATINSPFLAG="batteryInspFlag";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_BRAKENSPFLAG="brakesInspFlag";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_MILEAGE="mileage";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_SERVICEDATE="serviceDate";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_SERVICEDEALERID="serviceDealerID";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_SERVICETYPECODE="serviceTypeCode";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_SERVICETYPEDESC="serviceTypeDesc";
   public static final String SERVICE_REST_USER_VEHICLEHISTORY_RESPONSE_PARAMETER_SERVICEHISTORYRESPONSE_SERVICEHISTORYRETURN_VEHSERVICEDETAILS_SERHISTORYLIST_SERVICE_TIRESINSPFLAG="tiresInspFlag";


      // 4 GET VEHICLE MILEAGE REQUEST
   @Value("${MMG.SERVICE.SOAP.VEHICLE.MILEAGE}")
   public String SERVICE_SOAP_VEHICLE_MILEAGE;

   @Value("${MMG.SERVICE.SOAP.VEHICLE.MILEAGE.ACTION}")
   public String SERVICE_SOAP_VEHICLE_MILEAGE_ACTION;

   public static final String SERVICE_SOAP_VEHICLE_MILEAGE_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_REQUEST_PARAMETER_MILEAGEDETAILS="getMileageDetails";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_REQUEST_PARAMETER_MILEAGEDETAILS_VIN="vin";

    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS="getMileageDetailsResponse";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE="getMileageDetailsReturn";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_ERROR="error";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_DRIVINGCONDITIONS="drivingConditions";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_VIN="vin";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_CALCDATE="calcDate";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_MILEAGE="mileage";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_RESPONSE_PARAMETER_MILEAGEDETAILS_MILEAGE_MILESPERDAY="milesPerDay";

   // 5 UPDATE VEHICLE MILEAGE REQUEST
   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.MILEAGE}")
   public String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE;

   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.MILEAGE.ACTION}")
   public String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_ACTION;

   public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS="setMileageDetails";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS="mileageCounter";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_ERROR="error";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_DRIVINGCONDITIONS="drivingConditions";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_VIN="vin";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_CALCDATE="calcDate";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_MILEAGE="mileage";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_REQUEST_PARAMETER_SETMILEAGEDETAILS_SETMILEAGEDETAILS_MILESPERDAY="milesPerDay";

    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_RESPONSE_PARAMETER_MILEAGERESPONSE="setMileageDetailsResponse";
    public static final String SERVICE_SOAP_VEHICLE_MILEAGE_UPDATE_RESPONSE_PARAMETER_MILEAGERESPONSE_MILEAGERETURN="setMileageDetailsReturn";


    // 6 Update set Serving Dealer Request
   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER}")
   public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER;

   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.ACTION}")
   public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_ACTION;

   public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER="updateServDlr";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER_CUSTOMER="cust";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER_CUSTOMER_CUSTOMERID="custId";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER_CUSTOMER_DEALERCODE="dlrCd";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER_CUSTOMER_SOURCE="source";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_REQUEST_PARAMETER_UPDATESERIVINGDEALER_CUSTOMER_VIN="vinCd";
    

    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSE_PARAMETER_UPDATESERVICINGDEALERRESPONSE="updateServDlrResponse";
    public static final String SERVICE_REST_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSE_PARAMETER_UPDATESERVICINGDEALERRESPONSE_SERVICINGDEALERRETURN="updateServDlrReturn";

    // Decalaration of RESPONSE CODE FOR ABOVE.
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.S01}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_S01;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.S01.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_S01_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E00}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E00;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E00.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E00_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E01}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E01;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E01.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E01_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E02}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E02;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E02.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E02_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E03}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E03;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E03.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E03_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E04}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E04;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E04.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E04_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E05}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E05;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E05.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E05_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E06}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E06;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.E06.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E06_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D01}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D01;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D01.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D01_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D02}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D02;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D02.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D02_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D03}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D03;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D03.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D03_MESSAGE;

     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D04}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D04;
     @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.SERVICINGDEALER.RESPONSE.D04.MESSAGE}")
     public String SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D04_MESSAGE;

     /**
      * This is the function for above Response Codes to determine the exact Description Message.
      * @param errorCode
      */
     public static String getResponseMessage(ApplicationConstants appConstants,String errorCode)
    {

         errorCode=errorCode.toUpperCase().trim();
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_S01))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_S01_MESSAGE;
         
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E00))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E00_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E01))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E01_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E02))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E02_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E03))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E03_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E04))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E04_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E05))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E05_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E06))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_E06_MESSAGE;

         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D01))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D01_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D02))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D02_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D03))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D03_MESSAGE;
         if(errorCode.equalsIgnoreCase(appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D04))
             return appConstants.SERVICE_SOAP_VEHICLE_UPDATE_SERVICINGDEALER_RESPONSECODE_D04_MESSAGE;

         return errorCode + " Code Detail not present.";
     }

     
   // 7 UPdate Ownership of Vehicle (Add or Remove Vehicle).
   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.OWNERSHIP}")
   public String SERVICE_SOAP_VEHICLE_UPDATE_OWNSERSHIP;

   @Value("${MMG.SERVICE.SOAP.VEHICLE.UPDATE.OWNERSHIP.ACTION}")
   public String SERVICE_SOAP_VEHICLE_UPDATE_OWNSERSHIP_ACTION;

   public static final String VEHICLE_OWNERSHIP_REQUEST_DISPOSAL_FLAG_ONE="1";
   public static final String VEHICLE_OWNERSHIP_REQUEST_DISPOSAL_FLAG_ZERO="0";

   public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP="updateOwnership";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER="owner";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_CUSTOMERID="custId";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_DISPOSALFLAG="disposalFlag";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_DISPOSALREASON="disposalReason";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_NEWCUSTOMERID="newCustId";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_RESALEDATE="resaledate";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_SOURCE="source";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_REQUEST_PARAMETER_UPDATEOWNERSHIP_OWNER_VIN="vinCd";

    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_RESPONSE_PARAMETER_UPDATEOWNERSHIPRESPONSE="updateOwnershipResponse";
    public static final String SERVICE_REST_VEHICLE_UPDATE_OWNERSHIP_RESPONSE_PARAMETER_UPDATEOWNERSHIPRESPONSE_UPDATEOWNSERSHIPRETURN="updateOwnershipReturn";


    // 8 Update Customer/Owner/User Details
   @Value("${MMG.SERVICE.SOAP.USER.UPDATE.DETAILS}")
   public String SERVICE_SOAP_USER_UPDATE_DETAILS;

   @Value("${MMG.SERVICE.SOAP.USER.UPDATE.DETAILS.ACTION}")
   public String SERVICE_SOAP_USER_UPDATE_DETAILS_ACTION;

   public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_REST_USER_UPDATE_DETAILS_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER="updateCustomer";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER="cust";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_RETURNEDEMAIL="returnedEmail";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_ADDRESSVALIDATION="addressValidation";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_ADDONZIP="addOnZip";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_SOURCE="source";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_ERROR="error";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_CUSTOMERID="custID";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_ADDRESSTYPE="addressType";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_CITY="city";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_COUNTRY="country";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_DONOTCALL="doNotCall";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_DONOTEMAIL="doNotEmail";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_EMAIL="email";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_EMAILTYPE="emailType";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_FIRSTNAME="firstName";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_HOMEPHONE="homePhone";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_INVALIDADDRESSFLAG="invalidAddressFlag";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_LASTNAME="lastName";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_MOBILEPHONE="mobilePhone";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_STATE="state";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_STREETADDRESS1="street1address";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_STREETADDRESS2="street2address";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_WORKPHONE="workPhone";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_WORKPHONEEXT="workPhoneExt";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_ZIP="zip";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_REQUEST_PARAMETER_UPDATECUSTOMER_CUSTOMER_DONOTCONTACT="doNotContact";


    public static final String SERVICE_REST_USER_UPDATE_DETAILS_RESPONSE_PARAMETER_UPDATECUSTOMERRESPONSE="updateCustomerResponse";
    public static final String SERVICE_REST_USER_UPDATE_DETAILS_RESPONSE_PARAMETER_UPDATECUSTOMERRESPONSE_UPDATECUSTOMERETURN="updateCustomerReturn";


    // 9 Get Coupons/Reminders
   @Value("${MMG.SERVICE.SOAP.USER.VEHICLE.COUPONS_REMINDERS}")
   public String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS;

   @Value("${MMG.SERVICE.SOAP.USER.VEHICLE.COUPONS_REMINDERS.ACTION}")
   public String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_ACTION;

   public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";

   // List of Parameters for above.
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA="getCouponData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA_CUSTOMERID="custId";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA_SOURCE="source";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA_VIN="vin";

    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA_SOURCE_COUPON="MNCCP";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_REQUEST_PARAMETER_GETCOUPONDATA_SOURCE_SERVICEREMINDER="MNCSR";

    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE="getCouponDataResponse";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN="getCouponDataReturn";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUNT="count";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_STATUS="status";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_SERVICEOFFERDATA="serviceOfferData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_SERVICEREMINDERDATA="serviceReminderData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_SERVICEREMINDERDATA_SERVICEREMINDER="ServiceReminder";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_LETTERCODE="letterCode";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_SERVICEREMTEXT="srText";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_CONTACTOFFERID="contactOfferId";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_SERVICEREMDATE="serviceReminderDate";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA="couponData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD="CouponData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_BLANKOFFER="blankOffer";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_COUPONHEADER1="couponHdr1";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_COUPONHEADER2="couponHdr2";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_COUPONNUMBER="couponNumber";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DETAILS="details";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DOLLAROFF="dollarOff";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_FREE="free";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT1="lineTxt1";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT2="lineTxt2";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT3="lineTxt3";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT4="lineTxt4";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT5="lineTxt5";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT6="lineTxt6";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT7="lineTxt7";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT8="lineTxt8";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT9="lineTxt9";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT10="lineTxt10";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT11="lineTxt11";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT12="lineTxt12";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT13="lineTxt13";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT14="lineTxt14";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT15="lineTxt15";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT16="lineTxt16";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT17="lineTxt17";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT18="lineTxt18";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT19="lineTxt19";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT20="lineTxt20";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT21="lineTxt21";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT22="lineTxt22";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT23="lineTxt23";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT24="lineTxt24";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LINETEXT25="lineTxt25";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_PCTOFF="pctOff";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_PRICETEXT="priceTxt";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_REGPRICE="regPrice";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_SPECPRICE="specPrice";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_STARTINGFROM="startingFrom";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERCODE="dlrCd";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LETTERCODE="letterCode";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_VIN="vinCd";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERNAME="dealerName";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERADDRESS="dealerAddress";
    // New Tags introduced by Ashwani on 10 August for incorportaing multiple SR Changes.
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERADDRESS1="dealerAddr1";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERADDRESS2="dealerAddr2";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERCITY="dealerCity";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERCOUNTRY="dealerCountry";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERSTATE="dealerState";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DEALERZIP="dealerZip";
    // These are the new things, which are added on 14 July, after confirmation with SULE & Ashwani.
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE1="textLine1";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE2="textLine2";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE3="textLine3";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE4="textLine4";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE5="textLine5";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE6="textLine6";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE7="textLine7";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE8="textLine8";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE9="textLine9";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE10="textLine10";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE11="textLine11";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE12="textLine12";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE13="textLine13";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE14="textLine14";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE15="textLine15";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE_TEXT="text";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE_LAYOUT="textLayout";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE_LAYOUT_DISCLIAMER="disclaimerID";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE_LAYOUT_LINEFORMATCODE="lineFormatCode";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_TEXTLINE_LAYOUT_LINETYPECODE="lineTypeCode";
    // Added on 15th July.
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_FULLCIRCLEDATA="fullCircleData";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_FULLCIRCLEDATA_BRAKE="brakeFlag";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_FULLCIRCLEDATA_TIRE="tireFlag";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_FULLCIRCLEDATA_SERVICEDATE="serviceDt";
    // Added on 16th July
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_EXPIRATIONDATE="expirationDate";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_DISCLAIMER="disclaimerID";
    // Added on 16th September
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_HEADERTEXT="headerText";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_HEADERTEXT_TEXT="Text";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_LEFTHEADER="leftHeader";
    public static final String SERVICE_SOAP_VEHICLE_COUPONSREMINDERS_RESPONSE_PARAMETER_COUPONDATARESPONSE_COUPONDATARETURN_COUPONDATA_CD_RIGHTHEADER="rightHeader";    

    // For Getting DEALER Information.
   @Value("${MMG.SERVICE.SOAP.DEALER.INFO}")
   public String SERVICE_SOAP_DEALERINFO;

   @Value("${MMG.SERVICE.SOAP.DEALER.INFO.ACTION}")
   public String SERVICE_SOAP_DEALERINFOACTION;

   public static final String SERVICE_SOAP_DEALERINFO_REQUESTELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSEELEMENT_NAMESPACE="http://webservices.marketing.mazdausa.com";
   
   
   // List of parameters for above SOAP URL
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_MAZDADEALERINFORESPONSE="getMazdaDealerInfoResponse";
   public static final String SERVICE_SOAP_DEALERINFO_REQUEST_MAZDADEALERINFO="getMazdaDealerInfo";
   public static final String SERVICE_SOAP_DEALERINFO_REQUEST_MAZDADEALERINFO_DEALERCODE="dealerCd";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_RESPONSE="getMazdaDealerInfoReturn";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER="Dealer";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_CITY="city";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_CODE="code";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_COUNTRY="country";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_DISTRICT="district";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_ERRORSTATUS="errorStatus";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_EXCLUSIVE="exclusive";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_FACTORYORDERONLY="factoryOrderOnly";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_MACDEALERCODE="MACDealerCode";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_METROGROUP="metroGroup";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_NAME="name";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_PHONE="phone";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_PHONEAREACODE="phoneAreaCode";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_PHONEPREFIX="phonePrefix";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_PHONESUFFIX="phoneSuffix";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_SERVICEONLYFIG="serviceOnlyflg";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_STATE="state";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_STATUS="status";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_ADDRESS="strAddress";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_VOLUMEGROUP="volumeGroup";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_ZIP="zip";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_REGIONCODE="regionCd";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_REGIONNAME="regionName";
   public static final String SERVICE_SOAP_DEALERINFO_RESPONSE_DEALER_EXPSERFLAG="expServiceFlag";


   //For getting egift details
   @Value("${MMG.SERVICE.SOAP.GETEGIFTS}")
   public String SERVICE_SOAP_GETEGIFTS;
   
   @Value("${MMG.SERVICE.SOAP.GETEGIFTS.ACTION}")
   public String SERVICE_SOAP_GETEGIFTS_ACTION;
   
   public static final String SERVICE_SOAP_GETEGIFTS_REQUESTELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";
   public static final String SERVICE_SOAP_GETEGIFTS_RESPONSEELEMENT_NAMESPACE="http://webservices.vehicles.marketing.mazdausa.com";

   //Request parameter for get egifts
   public static final String XML_SOAP_GETEGIFTS_REQUEST_PARAMETER_GETEGIFTS="getEgifts";
   public static final String XML_SOAP_GETEGIFTS_REQUEST_PARAMETER_GETEGIFTS_CUSTOMERID="customerId";
   public static final String XML_SOAP_GETEGIFTS_REQUEST_PARAMETER_GETEGIFTS_VIN="vin";

   //Response parameter
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS="getEgiftsResponse";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN="getEgiftsReturn";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_ERROR="error";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS="EgiftDetails";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_COUNT="count";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST="eGiftList";

   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT="Egift";



   //List of parameters for above
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_CERTIFICATENO="certificateNo";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_AMOUNT="amount";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_ISSUEDATE="issueDate";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_REDEMPTIONAMOUNT="redemptionAmount";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_REDEMPTIONDATE="redemptionDate";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_EXPIRATIONDATE="expirationDate";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_EGIFTSTATUS="egiftStatus";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_VINNO="vinNo";
   public static final String XML_SOAP_GETEGIFTS_RESPONSE_PARAMETER_GETEGIFTS_GETEGIFTSRETURN_EGIFTDETAILS_EGIFTLIST_EGIFT_DEALERNAME="dealerName";   


   /**
    * List of all the Messages are being returned to the client.
    */
   @Value("${MMG.MESSAGE.USER.REGISTRATION.SUCCESS}")
   public String CLIENT_MESSAGE_REGISTRATION_SUCCESS;

   @Value("${MMG.NOMESSAGE.USER.REGISTRATION.SUCCESS}")
   public String CLIENT_NO_MESSAGE_REGISTRATION_SUCCESS;

   @Value("${MMG.MESSAGE.USER.LOGIN.SUCCESS}")
   public String CLIENT_MESSAGE_LOGIN_SUCCESS;

   @Value("${MMG.MESSAGE.USER.LOGIN.FAILURE}")
   public String CLIENT_MESSAGE_LOGIN_FAILURE;


   /**
    * Here is a list of Custom Properties that are being defined by the SULE
    */
   @Value("${MMG.CUSTOM.MESSAGE.SERVICEREMINDERS.DEFAULT.TEXT}")
   public String MMG_CUSTOM_MESAGE_SERVICE_REMINDERS_DEFAULT_TEXT;

   @Value("${MMG.CUSTOM.MESSAGE.SERVICEREMINDERS.COUPON.DEFAULT.LINETEXT}")
   public String MMG_CUSTOM_MESSAGE_SERVICEREMINDERS_COUPON_DEFAULT_LINETEXT;

   @Value("${MMG.CUSTOM.MESSAGE.COUPON.DISCLAIMER.DEFAULT.TEXT}")
   public String MMG_CUSTOM_MEESAGE_COUPON_DISCLAIMER_DEFAULT_TEXT;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.GREEN}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_GREEN;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.GREEN.DESCRIPTION}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_GREEN_DESCRIPTION;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.YELLOW}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_YELLOW;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.YELLOW.DESCRIPTION}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_YELLOW_DESCRIPTION;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.RED}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_RED;

   @Value("${MMG.MESSAGE.TIRE.BRAKE.CONDITION.CODE.RED.DESCRIPTION}")
   public String MMG_CODE_TIRE_BRAKE_CONDITION_RED_DESCRIPTION;

   @Value("${MMG.MESSAGE.DEALER.DEFAULT.DEAL}")
   public String DEALER_COUPON_PRICE_SAVE;
   /**
    * List of all the constants that is being stored in the Database Constants Table.
    */
   public static final String DATABASE_CONSTANT_MMGVEHICLECODE_UPDATEDTIME="MMGVEHICLECODE_UPDATEDTIME";

   /*
    * Constant is added on 09/08/2011 to avoid duplication of coupon line text code.
    */
   public static final String SERVICEREMINDER_LINETEXT_LAYOUT_TYPECODE_CONSTANT = "H";

   /*
    * Constant is added on 09/08/2011 for displaying error message in service reminder
    */
   @Value("${MMG.CUSTOM.MESSAGE.SERVICEREMINDERS.ERROR.MESSAGE}")
    public String MMG_CUSTOM_MESSAGE_SERVICEREMINDERS_ERROR_MESSAGE;


   /**
    * Service Reminder Letter Code Constants and their Values. Introduced on 02 Nov 2011.
    */
   @Value("${MMG.SERVICEREMINDER.LETTERCODE.10}")
   public String MMG_SERVICEREMINDER_LETTERCODE_10;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.10.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_10_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1A}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1A;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1A.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1A_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1AFC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1AFC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1AFC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1AFC_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1AUFC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1AUFC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1AUFC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1AUFC_VALUE;

    @Value("${MMG.SERVICEREMINDER.LETTERCODE.1B}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1B;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1B.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1B_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1BFC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1BFC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.1BFC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_1BFC_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.2}")
   public String MMG_SERVICEREMINDER_LETTERCODE_2;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.2.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_2_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.2FC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_2FC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.2FC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_2FC_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.3}")
   public String MMG_SERVICEREMINDER_LETTERCODE_3;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.3.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_3_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.5}")
   public String MMG_SERVICEREMINDER_LETTERCODE_5;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.5.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_5_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.5FC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_5FC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.5FC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_5FC_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.6}")
   public String MMG_SERVICEREMINDER_LETTERCODE_6;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.6.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_6_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.7}")
   public String MMG_SERVICEREMINDER_LETTERCODE_7;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.7.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_7_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.8}")
   public String MMG_SERVICEREMINDER_LETTERCODE_8;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.8.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_8_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.9}")
   public String MMG_SERVICEREMINDER_LETTERCODE_9;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.9.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_9_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.9FC}")
   public String MMG_SERVICEREMINDER_LETTERCODE_9FC;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.9FC.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_9FC_VALUE;

   @Value("${MMG.SERVICEREMINDER.LETTERCODE.DEFAULT.VALUE}")
   public String MMG_SERVICEREMINDER_LETTERCODE_DEFAULT_VALUE;


   /*
    * Constant for special coupon added on 04th NOV 2011
    */
   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.5}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_5;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.14}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_14;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.22}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_22;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.24}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_24;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.32}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_32;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.39}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_39;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.NUMBER.229}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_NUMBER_229;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON.STATIC.PRICETEXT}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON_STATIC_PRICETEXT;

   @Value("${MMG.SERVICEREMINDER.SPECIAL.COUPON}")
   public String MMG_SERVICEREMINDER_SPECIAL_COUPON;
   /*
    * Added on 11/11/2011
    */
   public static final String COUPON_SERVICEREMINDER_FORMATCODE_RTITLE = "RTITLE";

   /*
    * Added on 7/12/2011
    */
   public static final int DEALERCOUPON_SERVICEREMINDER_PRICE_TEXT_LENGTH = 14;
   public static final int DEALERCOUPON_SERVICEREMINDER_ANDROID_PRICE_TEXT_LENGTH = 46;
   
   public static final String MMG_STRING_BR_TAG = "<br />";
   public static final String MMG_STRING_BR_TAG_WITHOUT_SPACE = "<br/>";
   public static final String MMG_STRING_BR_TAG_WITHOUT_SPACE_SLASH = "<br>";

   public static final String MMG_CONSTANT_MODULE_NAME_YEAR_MODEL="YEARMODEL";   

   @Value("${MMG.APP.CONSTANT.NAME}")
   public String MMG_APP_CONSTANT_NAME;
   @Value("${MMG.APP.CONSTANT.VALUE}")
   public String MMG_APP_CONSTANT_VALUE;
   @Value("${MMG.APP.CONSTANT.ADDEDBY.NAME}")
   public String MMG_APP_CONSTANT_ADDEDBY_NAME;
   @Value("${MMG.APP.CONSTANT.MODULE.NAME}")
   public String MMG_APP_CONSTANT_MODULE_NAME;

   // Adding scan time out limit and message constant
   @Value("${MMG.SCAN.TIME.OUT.LIMIT}")
   public String MMG_SCAN_TIME_OUT_LIMIT;
   @Value("${MMG.SCAN.TIME.OUT.MESSAGE}")
   public String MMG_SCAN_TIME_OUT_MESSAGE;
   
   
   //Adding Mazda express service parameters
   @Value("${MMG.IMG.EXP.SERVICE}")
   public String MMG_IMG_EXP_SERVICE;
   @Value("${MMG.IMG.EXP.SERVICE.XX}")
   public String MMG_IMG_EXP_SERVICE_XX;
   @Value("${MMG.IMG.EXP.SERVICE.X}")
   public String MMG_IMG_EXP_SERVICE_X;
   
   @Value("${MMG.EXP.SERVICE.HTML}")
   public String MMG_EXP_SERVICE_HTML;
   @Value("${MMG.EXP.SERVICE.VER}")
   public String MMG_EXP_SERVICE_VER;
   
   //Adding Customer Support Info
   @Value("${MMG.CUSTOMER.SUPPORT.EMAIL}")
   public String MMG_CUSTOMER_SUPPORT_EMAIL;

   @Value("${MMG.CUSTOMER.SUPPORT.EMAIL_ALLOW}")
   public String MMG_CUSTOMER_SUPPORT_EMAIL_ALLOW;
   
   @Value("${MMG.CUSTOMER.SUPPORT.PHONE}")
   public String MMG_CUSTOMER_SUPPORT_PHONE;
   
   @Value("${MMG.CUSTOMER.SUPPORT.CRASHAGREEMENT.MESSAGE}")
   public String MMG_CUSTOMER_SUPPORT_CRASHAGREEMENT_MESSAGE;

   @Value("${MMG.CUSTOMER.SUPPORT.CRASHLOGDIR.IPHONE}")
   public String MMG_CUSTOMER_SUPPORT_CRASHLOGDIR_IPHONE;

   @Value("${MMG.CUSTOMER.SUPPORT.CRASHLOGDIR.ANDROID}")
   public String MMG_CUSTOMER_SUPPORT_CRASHLOGDIR_ANDROID;
   
   
  //Adding security token for Rest services @ 25-06-2013
   
   @Value("${MMG.REST.SERVICES.HEADER.1V.KEY}")
   public String MMG_REST_SERVICES_HEADER_1V_KEY;

   @Value("${MMG.REST.SERVICES.HEADER.1V.VALUE}")
   public String MMG_REST_SERVICES_HEADER_1V_VALUE;

   @Value("${MMG.REST.SERVICES.HEADER.TOKEN.KEY}")
   public String MMG_REST_SERVICES_HEADER_TOKEN_KEY;

   @Value("${MMG.REST.SERVICES.HEADER.TOKEN.VALUE}")
   public String MMG_REST_SERVICES_HEADER_TOKEN_VALUE;

   @Value("${MMG.SERVICE.REST.VEHICLE.RECALLALERTJOB}")
   public  String SERVICE_REST_VEHICLE_RECALLALERTJOB;
  //Adding push notification properties @10-07-2013
   
   @Value("${MMG.PUSHNOTIFICATION.IPHONE.KEYSTORESSLP12.PATH}")
   public String MMG_PUSHNOTIFICATION_IPHONE_KEYSTORESSLP12_PATH;

   @Value("${MMG.PUSHNOTIFICATION.IPHONE.PASSWORD}")
   public String MMG_PUSHNOTIFICATION_IPHONE_PASSWORD;
   
   @Value("${MMG.PUSHNOTIFICATION.ANDROID.KEY}")
   public String MMG_PUSHNOTIFICATION_ANDROID_KEY;
   
  // Adding SSG service properties

   @Value("${MMG.SSG.BASEURL.XML}")
   public String MMG_SSG_BASEURL_XML;
   
   @Value("${MMG.SSG.BASEURL.IMG}")
   public String MMG_SSG_BASEURL_IMG;
   
   @Value("${MMG.SSG.BASEURL.VDO}")
   public String MMG_SSG_BASEURL_VDO;
   
  
   //Adding Q4 force upgrade service variables
   @Value("${MMG.CUSTOMER.SUPPORT.APPVERSION.ANDROID}")
   public String MMG_CUSTOMER_SUPPORT_APPVERSION_ANDROID;
   
   @Value("${MMG.CUSTOMER.SUPPORT.APPVERSION.IPHONE}")
   public String MMG_CUSTOMER_SUPPORT_APPVERSION_IPHONE;

   //Alert data
   @Value("${MMG.USER.MAINTENANCEREMINDER.ALERT}")
   public String MMG_USER_MAINTENANCEREMINDER_ALERT;
   
   //Adding Q4 JCI LINK
   @Value("${MMG.CUSTOMER.SUPPORT.URL.JCILINK}")
   public String MMG_CUSTOMER_SUPPORT_URL_JCILINK;
      
   @Value("${MMG.VEHICLE.BASEURL.IMG}")
   public String MMG_VEHICLE_BASEURL_IMG;
   
   //Cover images for web browsers
   
   @Value("${MMG.VEHICLE.BASEURL.IMG.WEB}")
   public String MMG_VEHICLE_BASEURL_IMG_WEB;
   
   @Value("${MMG.VEHICLE.BASEURL.IMG.WEB.IPAD}")
   public String MMG_VEHICLE_BASEURL_IMG_WEB_IPAD;
   
   @Value("${MMG.VEHICLE.BASEURL.IMG.WEB.IPHONE}")
   public String MMG_VEHICLE_BASEURL_IMG_WEB_IPHONE;
   
   @Value("${MMG.VEHICLE.BASEURL.IMG.WEB.ANDROID}")
   public String MMG_VEHICLE_BASEURL_IMG_WEB_ANDROID;
   
   
   // Adding SSG service properties for Web clients

   @Value("${MMG.SSG.BASEURL.XML.WEB}")
   public String MMG_SSG_BASEURL_XML_WEB;
   
   @Value("${MMG.SSG.BASEURL.IMG.WEB}")
   public String MMG_SSG_BASEURL_IMG_WEB;
   
   @Value("${MMG.SSG.BASEURL.VDO.WEB}")
   public String MMG_SSG_BASEURL_VDO_WEB;
   
   // Adding SSG service properties for Web IPAD clients

   @Value("${MMG.SSG.BASEURL.XML.WEB.IPAD}")
   public String MMG_SSG_BASEURL_XML_WEB_IPAD;
   
   @Value("${MMG.SSG.BASEURL.IMG.WEB.IPAD}")
   public String MMG_SSG_BASEURL_IMG_WEB_IPAD;
   
   // Adding SSG service properties for Web IPHONE clients

   @Value("${MMG.SSG.BASEURL.XML.WEB.IPHONE}")
   public String MMG_SSG_BASEURL_XML_WEB_IPHONE;
   
   @Value("${MMG.SSG.BASEURL.IMG.WEB.IPHONE}")
   public String MMG_SSG_BASEURL_IMG_WEB_IPHONE;
   
   // Adding SSG service properties for Web ANDROID clients

   @Value("${MMG.SSG.BASEURL.XML.WEB.ANDROID}")
   public String MMG_SSG_BASEURL_XML_WEB_ANDROID;
   
   @Value("${MMG.SSG.BASEURL.IMG.WEB.ANDROID}")
   public String MMG_SSG_BASEURL_IMG_WEB_ANDROID;
   
   @Value("${MMG.USER.VEHICLE.IMAGE.UPLOAD.PATH}")
   public String MMG_USER_VEHICLE_IMAGE_UPLOAD_PATH;
   
}//End of class





