/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.emm.v1.mobile.vo;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * This is the Class, which will contain the session and the TOKEN for a particular session as generated by the client.
 * @author PankajB
 */
public class EmmSessionTokenVO {

    private String sessionid,tokenid;

    public String getSessionid() {
        return sessionid;
    }

    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    public String getTokenid() {
        return tokenid;
    }

    public void setTokenid(String tokenid) {
        this.tokenid = tokenid;
    }



}
